---
- name: Install Tinyproxy for web access
  yum:
    name: tinyproxy
    state: present

- name: Setup Tinyproxy Config file
  template:
    src: tinyproxy.conf.j2
    dest: /etc/tinyproxy.conf
  notify:
    - restart tinyproxy

- name: Ensure Tinyproxy is running
  service:
    enabled: yes
    name: tinyproxy
    state: started
