---
# $Author$
# $Date$
# $Source$


###############################################
# Tinyproxy installation & configuration role #
###############################################

- name: Dump the variables / facts known by Ansible for the Tinyproxy role
  include_role:
    name: mdrotthoff.ansible-debug

- name: Install Tinyproxy for web access
  yum:
    name: "{{ tinyproxy_package_name }}"
    state: "{{ tinyproxy_package_state }}"
  notify:
    - Restart Tinyproxy

- name: Create the directory for the Tinyproxy log file
  file:
    path: "{{ tinyproxy_logging.path }}"
    state: directory
    owner: "{{ tinyproxy_os_user }}"
    group: "{{ tinyproxy_os_group }}"
  when: tinyproxy_logging is defined

- name: Setup Tinyproxy Config file
  template:
    src: tinyproxy.conf.j2
    dest: "{{ tinyproxy_conf }}"
  notify:
    - Restart Tinyproxy

#- name: Ensure Tinyproxy is running
#  service:
#    enabled: yes
#    name: tinyproxy
#    state: started

- name: Configure logrotate to ensure the Tinyproxy log files remain under control
  include_role:
    name: mdrotthoff.logrotate
  vars:
    logrotate_scripts:
      - name: tinyproxy
        paths:
          - "{{ tinyproxy_log_path }}/{{ tinyproxy_log_file }}"
        options:
          - missingok
          - compress
          - delaycompress
          - notifempty
